email:
  fromEmail:
    address: "fromEmail@gmail.com"
    password: "password"
  toEmail:
    address: "toEmail@gmail.com"

redfin:
  searchUrl: "https://www.redfin.com/city/10943/MN/Minneapolis/filter/property-type=multifamily"




